edificeio/blog

src/main/java/org/entcore/blog/Blog.java, src/main/java/org/entcore/blog/explorer/PostExplorerPlugin.java, src/test/java/org/entcore/blog/BlogExplorerPluginClientTest.java
Appel au nouveau `RepositoryEvents` de l'EUR pour indexer les resources importés par workspace.
WB2-959
1. Export an archive containing blogs from recette or preprod
2. Import this archive in the targeted ENT
3. Imported resources are visible in Blog homepage
- Security flaws
- Performance impacts (think bulk !)
- Unit tests were replayed
- Unit tests were added and/or changed
- I have updated the reminder for the version including my modifications
=> [ODE] Importer les ressources importées depuis workspace

src/main/java/org/entcore/blog/explorer/BlogExplorerPlugin.java
Lors de la modification des propriétés d'une resource, les droits de partages sont vidés parce que la valeur par défaut des droits est un tableau vide, qui est interprété par l'EUR comme le fait de vider les droits de partages. La valeur par défaut `[]` a donc été remplacé par un `null` qui a l'effet escompté (ne rien faire sur les partages quand on n'a pas d'informations à leur sujet).
WB2-996
Le test du ticket
- Security flaws
- Performance impacts (think bulk !)
- Unit tests were replayed
- Unit tests were added and/or changed
- I have updated the reminder for the version including my modifications
=> [ODE] Ne pas réécrire les droits de partages après la modification des propriétés d'une ressource #365

src/main/resources/i18n/fr.json
Ajout des clefs de traduction dans blog pour le component `EmptyScreenApp` 
Ticket : #WB2-1066
https://edifice-community.atlassian.net/jira/software/c/projects/WB2/boards/41?modal=detail&selectedIssue=WB2-1066&assignee=712020%3A10bcae25-bc57-4d87-bad7-d00cf4320f32
=> feat: #WB2-1066, add trad key blog for EmptyScreen component

src/main/java/org/entcore/blog/Blog.java, src/main/java/org/entcore/blog/explorer/PostExplorerPlugin.java, src/main/java/org/entcore/blog/services/impl/DefaultPostService.java, src/test/java/org/entcore/blog/BlogExplorerPluginTest.java, src/test/java/org/entcore/blog/PostServiceContentTransformerTest.java
Ticket : https://edifice-community.atlassian.net/browse/WB-2008
Dans le cas de la création ou de la mise à jour de contenu de billets de blog, on récupère une version **plain text** (et non plus html) du contenu qui sera désormais transmis à l'explorateur pour l'indexation. Ce contenu plain text sera stocké dans un champ **content** de la base ES.
Ont dû être mis à jour :
- entcore : https://github.com/opendigitaleducation/entcore/pull/391
- explorer : https://github.com/opendigitaleducation/explorer/pull/27
Tests : 
- mise à jour des tests mixtes associés au plugin explorateur
- tests dev manuels
=> WB-2008 providing plain text content to explorer for indexation

src/main/java/org/entcore/blog/services/impl/DefaultPostService.java, src/test/java/org/entcore/blog/BlogExplorerPluginTest.java, src/test/java/org/entcore/blog/PostServiceContentTransformerTest.java
Ticket associé : https://edifice-community.atlassian.net/browse/WB-2007
Petite adaptation consistant à renvoyer au front seulement le contenu HTML "nettoyé", étant donné qu'il est le seul format à être consommé pour l'instant.
Les contenus aux formats JSON & PLAIN sont toutefois bien persistés en base.
Tests : 
-  adaptation & affinage des tests mixtes concernés
- correction de tests mixtes non liés mais qui ne passaient plus [ici](https://github.com/opendigitaleducation/blog/blob/c4e77cf53cf6c62097ad58224f19f765feeaabcf/src/test/java/org/entcore/blog/BlogExplorerPluginTest.java#L361C39-L361C39) et [ici](https://github.com/opendigitaleducation/blog/blob/c4e77cf53cf6c62097ad58224f19f765feeaabcf/src/test/java/org/entcore/blog/BlogExplorerPluginTest.java#L326) 
- tests manuels dev
=> WB-2007 returning only content version and cleaned html to frontend

src/main/java/org/entcore/blog/explorer/PostExplorerPlugin.java
Override `getCreatedAtColumn()` in class `PostExplorerPlugin` to set the return value to `created` which is the actual name in mongo
=> [EDIFICE] Specify createAt column for posts

.gitignore, build.gradle, gradle.properties, src/main/java/org/entcore/blog/controllers/PostController.java, src/main/java/org/entcore/blog/services/PostService.java, src/main/java/org/entcore/blog/services/impl/DefaultPostService.java, src/main/java/org/entcore/blog/to/PostFilter.java, src/test/java/org/entcore/blog/BlogExplorerPluginTest.java, src/test/java/org/entcore/blog/PostServiceContentTransformerTest.java
Sauvegarder en base de données le résultat de l'appel au transformateur de contenu pour les publications de blogs ayant été créés avant l'arrivée du nouvel éditeur et n'ayant pas encore été migrés.
[WB-2294](https://edifice-community.atlassian.net/browse/WB-2294)
[WB-2294]: https://edifice-community.atlassian.net/browse/WB-2294?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [EDIFICE] Ajout d'un cache au service de transformation

frontend/src/routes/index.tsx, frontend/src/routes/old-format/index.tsx, frontend/src/routes/post/index.tsx, frontend/vite.config.ts
* A new route path analyses the current location fragment (hash) to detect the following patterns : 
`#/view/:blogId` => redirects to the blog view,
`#/detail/:blogId/:postId` => redirects to post view
If a hash is found but not recognized, an error page will be displayed.
* The vite-server config file won't let `/blog#`-type URLs be proxified (for local dev)
=> feat: #WB-2335, route hash-based URLs

backend/src/main/java/org/entcore/blog/security/BlogResourcesProvider.java
Corrige une NPE lors de la vérification des droits d'accès à un post partagé
=> fix: WB-2582, avoid null pointer on shared posts rights

frontend/src/features/ActionBar/useActionDefinitions.ts, frontend/src/features/ActionBar/usePostActions.tsx, frontend/src/features/Post/CreatePost.tsx
Ce commit réapplique la logique historique requise côté frontend pour appeler les endpoints de publication/soumission de billet  adéquats côté backend.
Ne pas appliquer cette logique provoquait des régressions (ex: tickets soumis publiés, ou tickets publiés soumis...)
=> feat: #WB-2642, apply previous logic to publish or submit a post

frontend/src/config/index.ts, frontend/src/config/postCommentActions.ts, frontend/src/features/ActionBar/useActionDefinitions.ts, frontend/src/features/Comments/CommentsCreate.tsx, frontend/src/features/Comments/CommentsHeader.tsx, frontend/src/features/Comments/CommentsList.tsx, frontend/src/hooks/useComments.tsx, frontend/src/models/comment.ts
* adapt margins to respect designed UI when comments are visible / hidden...
* blog authors can also delete comments (like a manager)
* unified canComment / canContrib computation.
=> fix: WB-2256, apply shared right on comment zone

frontend/src/components/ButtonGroup/ButtonGroup.tsx, frontend/src/components/ButtonsGroup/ButtonsGroup.tsx, frontend/src/components/CommentCard/CommentCard.tsx, frontend/src/components/PostPreview/PostPreview.tsx, frontend/src/features/Blog/BlogActionBar.tsx, frontend/src/features/Comments/CommentsCreate.tsx, frontend/src/features/Post/CreatePost.tsx, frontend/src/features/Post/PostContent.tsx, frontend/src/features/Post/PostTitle.tsx, frontend/src/styles/index.css
Suite à évo du design system, j'ai factorisé du code redondant dans un nouveau composant.
Reste à voir si on l'extrait dans edifice-ui ensuite.
Le fix contient aussi 
* une correction de la navigation liée au bouton Retour depuis un post (comme spécifié dans la fonc fonctionnelle)
* des retours UX sur la CommentCard
* des retours UI sur les séparateurs (la classe CSS border-gray-600... n'existait pas !)
=> fix: WB-2255, new ButtonsGroup component applied

backend/src/main/java/org/entcore/blog/controllers/BlogController.java, frontend/src/components/PostPreview/PostPreview.tsx, frontend/src/components/PostPreview/PostPreviewActionBar.tsx, frontend/src/features/ActionBar/ActionBarContainer.tsx, frontend/src/features/ActionBar/useActionDefinitions.ts, frontend/src/features/Blog/BlogActionBar.tsx, frontend/src/features/Blog/BlogPostList.tsx, frontend/src/features/Blog/BlogSidebar.tsx, frontend/src/features/Post/PostContent.tsx, frontend/src/routes/index.tsx, frontend/src/routes/page-error/index.tsx, frontend/src/routes/post/index.tsx, frontend/src/routes/public-blog-print/index.tsx, frontend/src/routes/public-blog/index.tsx, frontend/src/routes/public-page-error/index.tsx, frontend/src/routes/public-portal/index.tsx, frontend/src/routes/public-post-print/index.tsx, frontend/src/routes/public-post/index.tsx, frontend/src/services/api/blog.ts, frontend/src/services/api/post.ts, frontend/src/services/queries/blog.tsx, frontend/src/services/queries/post.tsx
Les blogs public utilisent des endpoints différents, et des rendus sans Layout (sans portal).
Il a fallu adapter les composants et les Query associées, et notamment :
* adapter à React le endpoint (rétro-compatible) pour afficher un blog public,
* adapter à React le endpoint pour imprimer un blog public,
* ajouter un endpoint pour imprimer un billet de blog public,
Ces 2 derniers sont requis car on ouvre la page "print" d'un blog ou d'un billet dans un nouvel onglet, 
ce qui envoie une requête au backend pour charger le index.html. Ce endoint doit donc exister.
* support des routes frontend pour visualiser un blog / détail de billet public
* support des routes frontend pour imprimer un blog / détail de billet public
Ces routes utilisent le `slug` du blog, qui sert de discriminant au …
=> feat: WB-2688, public blog views

frontend/src/components/PostPreview/PostPreview.tsx, frontend/src/components/PostPreview/PostPreviewActionBar.tsx, frontend/src/features/Blog/BlogPostList.tsx, frontend/src/features/Blog/BlogSidebar.tsx, frontend/src/features/Post/PostContent.tsx, frontend/src/routes/public-blog-print/index.tsx, frontend/src/routes/public-blog/index.tsx, frontend/src/routes/public-portal/index.tsx, frontend/src/services/queries/blog.tsx
Avant le fix, on utilisait la visibilité du blog (PUBLIC ou non) ou sur la présence d'un slug comme discriminants, à différents endroits, et cela provoquait des inconsistences dans le rendu à l'écran ou les appels au backend.
=> fix: WB-2688, public blogs views are based on slug

frontend/src/components/PostPreview/PostPreviewActionBar.tsx
Ticket [WB-2715](https://edifice-community.atlassian.net/browse/WB-2715)
Depuis la barre d'action de la prévisualisation d'un billet, on ne doit pas pouvoir : 
* soumettre un billet déjà soumis à validation
* publier un billet déjà publié
* modifier/soumettre/publier/remonter un billet déjà en cours de mutation
[WB-2715]: https://edifice-community.atlassian.net/browse/WB-2715?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: #WB-2715, cannot submit an already submitted post

frontend/src/features/ActionBar/usePostActions.tsx, frontend/src/features/Post/PostActionBar.tsx, frontend/src/features/Post/PostTitle.tsx
Ticket [WB-2664](https://edifice-community.atlassian.net/browse/WB-2664)
In detailed view, 
* badge added, displaying the post state.
* the main action button is now contextual.
[WB-2664]: https://edifice-community.atlassian.net/browse/WB-2664?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: #WB-2664, display post's state in detailed view

frontend/src/features/Post/PostContent.tsx, frontend/src/hooks/usePostsFilter.ts
Ticket [WB-2818](https://edifice-community.atlassian.net/browse/WB-2818)
Utilisation de [useNavigate](https://reactrouter.com/en/6.22.3/hooks/use-navigate) pour mémoriser le statut du billet lorsqu’on presse “backward”, et de [useLocation](https://reactrouter.com/en/6.22.3/hooks/use-location) pour retrouver cette valeur au moment de réafficher la liste filtrée de billets.
[WB-2818]: https://edifice-community.atlassian.net/browse/WB-2818?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: #WB-2818, use navigation history to store a stateful value

frontend/src/routes/blog-root/index.tsx, frontend/src/routes/blog/index.tsx, frontend/src/routes/index.tsx, frontend/src/routes/post-print/index.tsx
Issue when checking rights to contrib before getting the blog.
Fix is to have common loader, which load the blog, for all blog routes.
>
>
>
=> fix: #WB-2850 get blog in all route before checking rights

frontend/src/components/PostPreview/PostPreviewActionBar.tsx, frontend/src/features/ActionBar/usePostActions.tsx, frontend/src/features/Post/CreatePost.tsx, frontend/src/features/Post/PostActionBar.tsx, frontend/src/features/Post/PostContent.tsx, frontend/src/utils/EditorHasContent.ts
Description : 
Ajout d'une fonction afin de vérifier si il y a du contenu dans l'éditeur. Obliger de faire cette vérification car sinon l'éditeur vide nous renvoie toujours un html `<p></p>`.
Ajout d'un boolean qui disable le bouton pour publier un post lorsque il n'y a rien dans l'éditeur + dans le titre.
Ajout d'un boolean qui disable le bouton enregistrer quand il n'y a rien de rempli mais reste activé lorsqu'il y a au moins un titre ou un contenu. 
Ajout d'un callback dans Editor pour écouter en direct si le content est rempli ou non, voir cette PR : https://github.com/edificeio/edifice-ui/pull/139
Tikcet : https://edifice-community.atlassian.net/browse/WB-2655
=> fix: #WB-2655, add function verify content editor + disable button if we can publish or save a post

frontend/src/features/Blog/BlogActionBar.tsx, frontend/src/features/Blog/BlogHeader.tsx, frontend/src/features/Post/PostActionBar.tsx
* Ajout de aria-labels sur les boutons "..." qui permettent d'afficher la barre d'action (pour les blogs et les billets)
* Uniformisation des Breadcrumb entre les pages blog et billet : suppression d'un bout de code qui s'activait en local uniquement (pratique, mais pas utile en prod)
=> fix: #WB-2793, add aria-labels where missing

frontend/src/features/ActionBar/usePostActions.tsx, frontend/src/features/Post/CreatePost.tsx, frontend/src/features/Post/PostContent.tsx, frontend/src/services/api/post.ts, frontend/src/services/queries/post.tsx, frontend/src/utils/BlogEvent.ts
> [Ticket WB-3068](https://edifice-community.atlassian.net/browse/WB-3068)
* Disabled buttons are showing a `<Loading/>` while mutating
* Better i18n for error toasts
>
>
=> fix: #WB-3068, better UX when saving a post without having a network connection

frontend/src/main.tsx, frontend/src/routes/public-portal/index.tsx, frontend/src/utils/disableLoginPageRedirection.ts
Getting the user session always throws a NOT_LOGGED_IN exception for disconnected users,
so application with public pages must "catch" and bypass it.
* Catching is done in react router error management, 
* it then launches an event so that public pages can "preventDefault" on it.
* The public-page lazy loader has put a listener for this event.
* and prevents its default (the redirection) => page loading can complete.
> Ticket WB-3157
>
>
=> fix: #WB-1357, allow access to public pages

frontend/src/features/ActionBar/usePostActions.tsx, frontend/src/features/Post/PostContent.tsx
As a manager, the save button label was not correct while modifying a post submitted by a contributor.
> [Ticket WB-3139](https://edifice-community.atlassian.net/browse/WB-3139)
>
>
=> fix: #WB-3139, change button label when a manager saves a submitted post

frontend/src/features/Post/PostContent.tsx
Le titre et le contenu d'un billet doivent être réinitialisés lorsque l'utilisateur annule sa saisie.
L'implémentation précédente ne gérait pas le titre, et ne détectait pas que le contenu avait changé : du coup, un `useEffect` dépendant du `content` ne se déclenchait pas et le contenu restait inchangé.
[Va de pair avec cette autre PR.](https://github.com/edificeio/edifice-ui/pull/255)
> [Ticket WB-3020](https://edifice-community.atlassian.net/browse/WB-3020)
>
>
=> fix: WB-3020, memoize updated content and title, and reset them on cancellation
