edificeio/blog

src/main/resources/public/ts/controller.ts

lié a https://github.com/web-education/blog/commit/df000b3fc08e48e89978c85c45b9c16766097fe0
Ticket : http://support.web-education.net/issues/21777

[Fix]#21777 make blog post printable only if published

---

build.gradle
deployment/blog/conf.json.template
docker-compose.yml
gradle.properties
src/main/java/org/entcore/blog/Blog.java
src/main/java/org/entcore/blog/services/impl/DefaultPostService.java
src/test/java/org/entcore/blog/BlogExplorerPluginClientTest.java
src/test/java/org/entcore/blog/BlogExplorerPluginTest.java
src/test/java/org/entcore/blog/BlogRepositoryEventTest.java
src/test/java/org/entcore/blog/FolderControllerExplorerTest.java
src/test/java/org/entcore/blog/PostServiceContentTransformerTest.java

Dans le cadre de l'arrivée du nouvel éditeur de contenu riche, mise en place côté blog de la sauvegarde des nouveaux champs `contentJson` et `contentVersion`.
- `contentJson`, le document JSON correspondant au contenu HTML de TipTap
- `contentVersion`, la version du document HTML. `0` pour du contenu jamais passé par TipTap, `1` pour du contenu déjà transformé.

[EDIFICE] Transformation du contenu riche

---

src/main/resources/public/ts/controller.ts

Suite au soucis remonté par Christophe : "On peut toujours ouvrir le blog si on clique sur le titre du billet du blog dans la notification alors que le blog est dans la corbeille."
Show 404 if user tries to access a post of a trashed Blog

fix: #WB2-1252, show 404 if user tries to access a post of a trashed Blog

---

src/main/java/org/entcore/blog/services/impl/DefaultPostService.java

Little fix on caching strategy when fetching blog posts

WB-2475 fixing cache implementation when fetching blog posts

---

src/main/java/org/entcore/blog/controllers/PostController.java
src/main/java/org/entcore/blog/services/PostService.java
src/main/java/org/entcore/blog/services/impl/DefaultPostService.java
src/test/java/org/entcore/blog/BlogExplorerPluginTest.java
src/test/java/org/entcore/blog/PostServiceContentTransformerTest.java

This enables temporarily current backend implementation with tip tap transformation to work with former version of front end

WB-2476 making backend with tip tap transformation compatible with old front end

---

backend/src/main/resources/i18n/fr.json
frontend/src/config/blogContentActions.ts
frontend/src/config/config.ts
frontend/src/features/ActionBar/Resource/ResourceModal.ts
frontend/src/features/ActionBar/useActionDefinitions.ts
frontend/src/features/Blog/BlogActionBar/BlogActionBar.tsx
frontend/src/models/blog.ts
frontend/src/services/api/index.ts
frontend/src/services/queries/index.tsx

Implentation Actions for blog:
- Add new post navigation
- Edit blog action

feat: #WB-2351 Add Edit blog action + Create post navigation

---

backend/gradle.properties
backend/src/main/java/org/entcore/blog/Blog.java
backend/src/main/java/org/entcore/blog/security/BlogResourcesProvider.java
backend/src/main/java/org/entcore/blog/services/PostService.java
backend/src/main/java/org/entcore/blog/services/impl/DefaultPostService.java

Feat mesure audience

---

backend/src/main/resources/i18n/fr.json
frontend/src/components/PostPreview/PostPreview.tsx
frontend/src/components/PostPreview/PostPreviewActionBar.tsx
frontend/src/features/ActionBar/useActionDefinitions.ts
frontend/src/features/ActionBar/usePostActions.tsx
frontend/src/features/Blog/BlogFilter.tsx
frontend/src/features/Blog/BlogPostList.tsx
frontend/src/features/Post/PostContent.tsx
frontend/src/routes/blog/index.tsx
frontend/src/routes/post-print/index.tsx
frontend/src/services/api/post.ts
frontend/src/services/queries/blog.tsx
frontend/src/services/queries/post.tsx
frontend/src/store/index.ts

Implement preview post actions from [ticket ](https://edifice-community.atlassian.net/browse/WB-2613)
- Print
- Edit
- Publish
- GoUp
- Delete

feat: #WB-2613 Add preview post actions

---

backend/gradle.properties
backend/src/main/java/org/entcore/blog/Blog.java
backend/src/main/java/org/entcore/blog/services/impl/DefaultBlogService.java
backend/src/main/java/org/entcore/blog/services/impl/DefaultPostService.java
backend/src/test/java/org/entcore/blog/BlogExplorerPluginClientTest.java
backend/src/test/java/org/entcore/blog/BlogExplorerPluginTest.java
backend/src/test/java/org/entcore/blog/BlogRepositoryEventTest.java
backend/src/test/java/org/entcore/blog/FolderControllerExplorerTest.java
backend/src/test/java/org/entcore/blog/PostServiceContentTransformerTest.java

Notification du module audience lors de la suppressions des ressources (posts) pour la purge des données.
https://edifice-community.atlassian.net/browse/WB-2569

WB-2569 purge audience

---

frontend/src/features/ActionBar/useActionDefinitions.ts
frontend/src/hooks/useBlogErrorToast.tsx
frontend/src/routes/blog/index.tsx
frontend/src/routes/post-edit/index.tsx
frontend/src/routes/post/index.tsx
frontend/src/services/queries/comment.tsx
frontend/src/services/queries/post.tsx
frontend/src/utils/BlogEvent.ts
frontend/src/utils/BlogEvent.tsx

* Prefer publishing over submitting when both are allowed.
* Fix immutability of a submitted post (feedback from slack).
* Display toasts on HTTP errors in blog and post views.

fix: #WB-2356, prefer publishing over submitting when both are allowed

---

frontend/src/components/CommentCard/CommentCard.tsx
frontend/src/features/Comments/CommentsCreate.tsx
frontend/src/features/Post/PostTitle.tsx
frontend/src/styles/index.css
frontend/src/utils/PostUtils.ts

* Refactored CommentCard design applied,
* post and comment authors displayed as hyperlinks (but with custom CSS),

feat: #WB-2638, post and comment authors as hyperlinks

---

frontend/src/components/CommentCard/CommentCard.tsx
frontend/src/features/Comments/CommentsList.tsx
frontend/src/features/Post/PostContent.tsx
frontend/src/features/Post/PostTitle.tsx
frontend/src/routes/post/index.tsx
frontend/src/styles/index.css

Fix some display errors
- max width
- comment text break
- margins
>
>
>

fix: #WB-2254 update margin, comment break, width

---

frontend/src/features/Post/PostContent.tsx
frontend/src/routes/post/index.tsx

[Ticket WB-2646](https://edifice-community.atlassian.net/browse/WB-2646)
* Les commentaires sont masqués lorsqu'on modifie un billet.
* Les commentaires sont alignés verticalement avec le billet.

feat: WB-2646, hide comments while editing a post

---

backend/src/main/java/org/entcore/blog/security/BlogResourcesProvider.java

Fix : contrôle d'accès à TOUS les posts

fix: WB-2582, must have access rights on ALL posts

---

frontend/src/routes/blog-print/index.tsx
frontend/src/routes/index.tsx
frontend/src/routes/old-format/index.tsx
frontend/src/routes/post-print/index.tsx
frontend/src/routes/post/index.tsx
frontend/src/routes/public-post-print/index.tsx
frontend/src/routes/public-post/index.tsx
frontend/src/services/queries/blog.tsx

Block trashed blog from being displayed
>
>
>

fix: #WB-2742 block trashed blog from being displayed

---

frontend/src/features/Blog/Blog.tsx
frontend/src/features/Blog/BlogHeader.tsx
frontend/src/features/Blog/BlogPrint.tsx
frontend/src/features/Post/PostTitle.tsx
frontend/src/hooks/useLoadPostList.tsx
frontend/src/routes/blog-print/index.tsx
frontend/src/routes/blog/index.tsx
frontend/src/routes/index.tsx
frontend/src/routes/post-print/index.tsx
frontend/src/routes/public-blog-print/index.tsx
frontend/src/routes/public-blog/index.tsx
frontend/src/routes/public-portal/index.tsx
frontend/src/routes/public-post/index.tsx

Update public page for blog and post to disabled actions.
Refacto some duplicate code used in route components.
>
>

fix: #WB-2699 disabled actions for blog public + refacto duplicate code for routes

---

frontend/src/features/ActionBar/usePostActions.tsx
frontend/src/features/Post/CreatePost.tsx
frontend/src/features/Post/PostContent.tsx

Ticket [WB-2698](https://edifice-community.atlassian.net/browse/WB-2698)
On se base sur l'état de la mutation React uery en cours, afin de griser les boutons à bloquer.
[WB-2698]: https://edifice-community.atlassian.net/browse/WB-2698?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: #WB-2698, cannot publish a blog post X times

---

backend/src/main/java/org/entcore/blog/controllers/PostController.java
backend/src/main/java/org/entcore/blog/services/PostService.java
backend/src/main/java/org/entcore/blog/services/impl/DefaultPostService.java

Permet de gérer la transformation du contenu des posts des blogs publiques lors de leur récupération

fix: transform content of public posts when fetching them

---

backend/src/main/java/org/entcore/blog/controllers/BlogController.java

Add backend route render view to react app for public blog post : `@Get("/pub/:slug/post/:postid")` to enable user to refresh page.

fix: #WB-2701, add public blog post route to render view to react app index

---

frontend/src/utils/EditorHasContent.ts

Ce fix corrige un problème de parsing des anciens contenus mal supportés, en s'assurant que le contenu en JSON est présent avant de tenter d'y accéder.
>
>
>

fix: #WB-2869, defensive programing while accessing to the jsonContent of a blog post

---

backend/src/main/resources/i18n/fr.json
frontend/src/features/ActionBar/useActionDefinitions.ts
frontend/src/features/ActionBar/usePostActions.tsx
frontend/src/features/Post/CreatePost.tsx
frontend/src/features/Post/PostContent.tsx
frontend/src/services/queries/post.tsx

- Some buttons had a bad label.
- The post's badge showing its state was sometimes wrong.
> [Ticket WB-2886](https://edifice-community.atlassian.net/browse/WB-2886)
>
>

fix: #WB-2886, save buttons label in create or edit mode

---

backend/build.gradle
backend/docker-compose.yml
backend/src/main/java/org/entcore/blog/security/BlogResourcesProvider.java
backend/src/main/java/org/entcore/blog/services/impl/DefaultPostService.java
backend/src/test/js/scenarios/shares.js
backend/src/test/js/utils.js

Only allow contributors to delete their posts.

[EDIFICE] Only allow contributors to delete their posts

---

backend/src/main/java/org/entcore/blog/services/impl/DefaultPostService.java

https://edifice-community.atlassian.net/browse/WB-3021
When a new blog post is published two requests are made : 
- a creation request of the post
- an update request of the post published status
The write concern is set to MAJORITY for these two mongo query, and the post update query, to make sure the data is correctly replicated for a quick subsequent read access.
>
>

fix: WB-3021, write concern set to MAJORITY when creating and publishing a post

---

frontend/src/components/CommentCard/CommentCard.tsx
frontend/src/styles/index.css

fix: #WB-3057 breakline in content

---

backend/src/main/java/org/entcore/blog/services/impl/DefaultBlogService.java

Normalisation des droits des blogs (ticket WB-3083).

[EDIFICE] normalize blog rights

---

frontend/src/features/ActionBar/useActionDefinitions.ts
frontend/src/features/ActionBar/usePostActions.tsx

> [Ticket WB-3071](https://edifice-community.atlassian.net/browse/WB-3071)
Le fix consiste à adapter la règle d'affichage du bouton permettant d'enregistrer en brouillon.
Cela passe par 
* l'export de la variable `isRestraint` depuis le hook _useActionDefinitions_, nécessaire à l'application de la règle de gestion,
* et le renommage d'une variable `isAuthor` qui n'était pas suffisamment explicite, à la relecture du code.
>
>

fix: #WB-3071, hide Draft button in very specific cases only

---

frontend/src/routes/blog-print/index.tsx
frontend/src/routes/blog-root/index.tsx
frontend/src/routes/index.tsx
frontend/src/routes/post/index.tsx
frontend/src/routes/public-portal/index.tsx
frontend/src/routes/public-post-print/index.tsx
frontend/src/routes/public-post/index.tsx
frontend/src/services/queries/blog.tsx

fix: #WB-3096 clean trash requests

---

frontend/src/components/PostPreview/PostPreview.tsx
frontend/src/features/ActionBar/usePostActions.tsx
frontend/src/features/Blog/BlogActionBar.tsx
frontend/src/features/Blog/BlogPostList.tsx
frontend/src/features/Blog/BlogPrint.tsx
frontend/src/features/Blog/BlogSidebar.tsx
frontend/src/features/Comments/CommentsHeader.tsx
frontend/src/features/Post/PostAudience.tsx
frontend/src/features/Post/PostContent.tsx
frontend/src/hooks/useLoadPostList.tsx
frontend/src/services/api/blog.ts
frontend/src/services/api/post.ts
frontend/src/services/queries/blog.tsx
frontend/src/store/index.ts
frontend/vite.config.ts

Ajout des appel API pour les vues + debut implem pour récupérer la liste des compteurs
>
>
>

feat: #WB-2998 add views counters

---

frontend/src/components/PostPreview/PostPreview.tsx
frontend/src/features/Post/PostAudience.tsx
frontend/src/features/Post/PostContent.tsx

* Integration of ReactionChoice
* Corrected alignments
* Better responsive mode
>
>

fix: #WB-3003, integrate reaction choice component et adjust alignments

---

frontend/src/components/PostPreview/PostPreview.tsx
frontend/src/styles/index.css

feat: #WB-2999 add open modal on click

---

frontend/src/components/PostPreview/PostPreview.tsx
frontend/src/features/Post/PostAudience.tsx
frontend/src/hooks/useReactionModal.ts

fix: #WB-3002, DRY for reaction modal

---

frontend/src/components/PostPreview/PostPreview.tsx
frontend/src/features/Post/PostAudience.tsx
frontend/src/hooks/useReactionSummary.ts

> [Ticket WB-2545](https://edifice-community.atlassian.net/browse/WB-2545)
>
>

feat: #WB-2545, add reaction modal to preview page

---

frontend/src/routes/root/index.tsx

Add a load if the init session and conf are not yet completed to be fetched

fix: add check if init loading is done

---

frontend/src/components/PostPreview/PostPreview.tsx
frontend/src/components/PostPreview/PostPreviewFooter.tsx
frontend/src/components/PostPreview/PostPreviewHeader.tsx
frontend/src/features/Blog/BlogPostList.tsx
frontend/src/features/Post/PostAudience.tsx
frontend/src/features/Post/PostContent.tsx
frontend/src/hooks/useReactionSummary.ts
frontend/src/services/queries/post.tsx
frontend/src/store/index.ts

fix: #WB-3001 refacto reaction components to use store + clean PostPreview component

---

frontend/src/components/PostPreview/PostPreview.tsx
frontend/src/components/PostPreview/PostPreviewFooter.tsx
frontend/src/features/Post/PostAudience.tsx
frontend/src/features/Post/PostContent.tsx
frontend/src/services/queries/blog.tsx
frontend/src/styles/index.css

fix: #WB-3158 audience fine tuning

---

backend/src/main/java/org/entcore/blog/controllers/PostController.java
backend/src/main/java/org/entcore/blog/security/BlogResourcesProvider.java
backend/src/main/java/org/entcore/blog/security/filter/comment/CommentAuthorFilter.java
backend/src/main/java/org/entcore/blog/security/filter/comment/CommentAuthorOrManagerFilter.java
backend/src/main/java/org/entcore/blog/security/filter/comment/CommentFilter.java
backend/src/test/js/scenarios/comments.js
backend/src/test/js/utils.js
frontend/src/features/Blog/Blog.tsx
frontend/src/routes/post/index.tsx

Les droits ressource sur les commentaires étaient trop laxistes (=> avec le droit, permettait de modifier tous les commentaires d'un billet) ou trop restrictifs (=> sans le droit, retiré ou perdu pour une obscure raison, on ne pouvait plus modifier ses propres commentaires), on a donc décidé de les personnaliser côté backend en suivant les règles métiers suivantes : 
* le créateur d’un blog ne peut pas modifier les commentaires de tiers laissés sur tout billet de ce blog.
* tout créateur d’un blog peut supprimer un commentaire sur n’importe quel billet de ce blog.
* le gestionnaire d’un blog ne peut pas modifier les commentaires de tierslaissés sur tout billet de ce blog.
* tout manager d’un blog peut supprimer un commentaire de n’importe quel billet de ce blog.
* tout créateur d’un …

fix : WB-3303, custom update and delete filters on comments

---

frontend/src/components/CommentCard/CommentCard.tsx
frontend/src/features/Post/PostTitle.tsx
frontend/src/styles/index.css

fix: #WB2-1900 remove link on author comment

---

backend/gradle.properties
backend/src/main/java/org/entcore/blog/Blog.java
backend/src/main/java/org/entcore/blog/services/impl/DefaultPostService.java
backend/src/test/java/org/entcore/blog/BlogExplorerPluginClientTest.java
backend/src/test/java/org/entcore/blog/BlogExplorerPluginTest.java
backend/src/test/java/org/entcore/blog/BlogRepositoryEventTest.java
backend/src/test/java/org/entcore/blog/FolderControllerExplorerTest.java
backend/src/test/java/org/entcore/blog/PostServiceContentTransformerTest.java
frontend/docker-compose.yml

La transformation de contenu riche nécessite les metadata suivantes :
* type de la ressource transformée
* ID de la ressource
> Ticket [WB-3286](https://edifice-community.atlassian.net/browse/WB-3286)
>
>
[WB-3286]: https://edifice-community.atlassian.net/browse/WB-3286?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[EDIFICE] Uncouple multimedia details recording from ContentTransformer client

---

frontend/src/components/CommentCard/CommentCard.tsx
frontend/src/features/Comments/CommentsCreate.tsx
frontend/src/features/Comments/CommentsList.tsx
frontend/src/features/Post/CreatePost.tsx
frontend/src/features/Post/PostContent.tsx
frontend/src/features/Post/PostDate.tsx
frontend/src/routes/post-edit/index.tsx
frontend/src/routes/post-print/index.tsx
frontend/src/routes/post/index.tsx
frontend/src/routes/public-post-print/index.tsx
frontend/src/routes/public-post/index.tsx

chore: #WB-3212 fragment usage

---

frontend/src/components/PostPreview/PostPreview.tsx
frontend/src/components/PostPreview/PostPreviewActionBar.tsx
frontend/src/components/PostPreview/PostPreviewAudienceFooter.tsx
frontend/src/components/PostPreview/PostPreviewReactionFooter.tsx
frontend/src/features/Blog/BlogActionBar.tsx
frontend/src/features/Blog/BlogPostList.tsx
frontend/src/features/Blog/BlogSidebar.tsx
frontend/src/features/Post/PostAudience.tsx
frontend/src/hooks/useLoadPostList.tsx
frontend/src/hooks/useReactionSummary.ts
frontend/src/services/queries/blog.tsx
frontend/src/store/index.ts

chore: #WB-3218 update zustand store usage

---

frontend/src/features/Blog/BlogHeader.tsx

chore: #WB-3223 correct AppHeader usage

---

frontend/src/features/Blog/BlogPostList.tsx
frontend/src/features/Blog/BlogPrint.tsx
frontend/src/features/Blog/BlogSidebar.tsx
frontend/src/hooks/useLoadPostList.tsx
frontend/src/services/queries/blog.tsx

chore: #WB-3217 remove audience call for public blog

---

frontend/src/routes/index.tsx
frontend/src/routes/root/index.tsx

Change the default path from "/*" to "/" to fix issue with location replace in Safari.
And small refactor to adjust code as in other apps for default route.
>
>

fix: #WB2-1922, fix default route path '/*' issue with Safari

---

frontend/src/utils/redirectBlogHashLocation.ts

Change the way to replace location in JS to fix Safari issue.
>
>

fix: #WB2-1922, fix location replace for Safari

---

backend/pom.xml
backend/src/main/java/org/entcore/blog/Blog.java
backend/src/main/java/org/entcore/blog/controllers/BlogController.java
backend/src/main/java/org/entcore/blog/listeners/ResourceBrokerListenerImpl.java
backend/src/main/java/org/entcore/blog/services/BlogService.java
frontend/package.json

Ce commit ajoute:
- un listener sur le broker pour récupérer les info concernant une ressource
- un listener permettant de partager/départager une ressource dans blog
>
>
>

Feat: #pedago-2699, link into community

---

backend/src/main/java/org/entcore/blog/Blog.java
backend/src/main/java/org/entcore/blog/explorer/BlogExplorerPlugin.java
backend/src/main/java/org/entcore/blog/services/impl/DefaultBlogService.java
backend/src/main/resources/view/index.html
backend/src/test/java/org/entcore/blog/BlogExplorerPluginClientTest.java
backend/src/test/java/org/entcore/blog/BlogExplorerPluginTest.java
backend/src/test/java/org/entcore/blog/BlogRepositoryEventTest.java
backend/src/test/java/org/entcore/blog/FolderControllerExplorerTest.java
backend/src/test/java/org/entcore/blog/PostServiceContentTransformerTest.java
frontend/package.json

Ce commit publie les event de suppression de blog sur le broker en utilisant le BrokerPublisher et la classe proxy BrokerPublisherRepository. Testé sur communauté
>
>
>

feat: #pedago-3019, publish delete event on broker

---

frontend/src/config/explorer.ts

Change workflow permission for copy action

fix: change-copy-workflow-permission
